### ISSUE TITLE
Unit tests failing with "AssertionError: If capturable=False, state_steps should not be CUDA tensors."

### ISSUE THREAD

**Issue by jithunnair-amd** [ROCmSoftwarePlatform/apex#82] opened 2022-08-05 15:49 UTC
test_adam_option (test_fused_optimizer.TestFusedAdam): due to https://github.com/pytorch/pytorch/issues/80809#issuecomment-1175211598
test_multi_device (test_fused_optimizer.TestFusedAdam): due to https://github.com/pytorch/pytorch/issues/80809#issuecomment-1175211598
test_float (test_fused_optimizer.TestFusedAdam): due to https://github.com/pytorch/pytorch/issues/80809#issuecomment-1175211598
test_bfloat16 (test_fused_optimizer.TestFusedAdam): due to https://github.com/pytorch/pytorch/issues/80809#issuecomment-1175211598

Reference: https://github.com/ROCmSoftwarePlatform/apex/pull/78#issuecomment-1201839061

**Comment by hubertlu-tw** [comment] 2022-08-05 18:28
The tests failed due to a regression introduced from PyTorch upstream: https://github.com/pytorch/pytorch/issues/80809#issuecomment-1175211598. They can be unskipped once the fix is integrated into PyTorch ROCm fork from PyTorch upstream.

**Closed** 2022-12-06 21:21 UTC
